# Generated by Django 4.1.3 on 2022-12-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Description', models.TextField()),
                ('amount', models.IntegerField()),
                ('img', models.ImageField(upload_to='menu/')),
                ('Date', models.DateTimeField()),
                ('subTitle', models.TextField(blank=True)),
            ],
        ),
    ]
