# Generated by Django 4.1.3 on 2023-01-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.TextField()),
                ('User', models.TextField(default='unknown')),
                ('title', models.TextField()),
                ('img', models.TextField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField()),
                ('users', models.TextField()),
                ('phonenumber', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.TextField()),
                ('address', models.TextField()),
                ('amount', models.TextField()),
                ('quant', models.TextField(default=1)),
                ('img', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Description', models.TextField()),
                ('amount', models.IntegerField()),
                ('img', models.ImageField(upload_to='menu/')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('subTitle', models.TextField(blank=True)),
                ('Ratting', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='catogory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BestMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Description', models.TextField()),
                ('amount', models.IntegerField()),
                ('img', models.ImageField(upload_to='menu/')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('subTitle', models.TextField(blank=True)),
                ('Ratting', models.FloatField(null=True)),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
                ('catogorys', models.ForeignKey(default='all', on_delete=django.db.models.deletion.CASCADE, to='app1.catogory')),
            ],
        ),
    ]
