# Generated by Django 4.1.3 on 2022-12-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestmenu',
            name='Ratting',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bestmenu',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
