# Generated by Django 4.1.3 on 2022-12-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_carouselslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.TextField(default='unknown')),
                ('title', models.TextField()),
                ('img', models.TextField()),
                ('food_id', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
