# Generated by Django 4.1.3 on 2023-01-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_addtocart_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField()),
                ('users', models.TextField()),
                ('phonenumber', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.TextField()),
                ('address', models.TextField()),
                ('amount', models.TextField()),
                ('quant', models.TextField(default=1)),
            ],
        ),
    ]
